#pragma config(Sensor, S2,     color,          sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S4,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          right,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          arm,           tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void lineFollow()
{
	//Creates variables to store the red, green, and blue values
	long redValue;
	long greenValue;
	long blueValue;

	//Loop
	int exit  = 0;
	while (exit == 0)
	{
		//Get the value of all three channels of the color sensor
		//and store it in the variables
		getColorRGB(color, redValue, greenValue, blueValue);

		displayBigTextLine(4, "colorBlue%d", redValue);
		int exitLine  = 0;
    if (exitLine == 0)
    {
			if( blueValue > 50)
			{
				motor(left) = 45;
				motor(right) = 5;
			}
			else
			{
				motor(left) = 5;
				motor(right) = 45;
			}
		}

		if(redValue < 20)
		{
			motor(right) = 0;
			motor(left) = 0;
			exitLine = 1;
		}
		if(exitLine == 1)
		{
			while(SensorValue(sonar) > 5)
			{
				motor(right) = 20;
				motor(left) = 20;
			}
		}

	}



}
task main()
{
 motor(right) = 20;
 motor(left) = 20;
 lineFollow();


}
