#pragma config(Sensor, S2,     color,          sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S4,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          right,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          arm,           tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void lineFollow()
{
	//Creates variables to store the red, green, and blue values
	long redValue;
	long greenValue;
	long blueValue;

	//Loop
	int exit  = 0;
	while (exit == 0)
	{
		//Get the value of all three channels of the color sensor
		//and store it in the variables
		getColorRGB(color, redValue, greenValue, blueValue);

		displayBigTextLine(4, "colorBlue%d", blueValue);
	}


}
task main()
{
 lineFollow();


}
